#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-find-bundle
Version  : 1.0.2
Release  : 1
URL      : https://github.com/aselker/clr-find-bundle/archive/v1.0.2.tar.gz
Source0  : https://github.com/aselker/clr-find-bundle/archive/v1.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: clr-find-bundle-bin
Requires: clr-find-bundle-license

%description
No detailed description available

%package bin
Summary: bin components for the clr-find-bundle package.
Group: Binaries
Requires: clr-find-bundle-license

%description bin
bin components for the clr-find-bundle package.


%package license
Summary: license components for the clr-find-bundle package.
Group: Default

%description license
license components for the clr-find-bundle package.


%prep
%setup -q -n clr-find-bundle-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534961264
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534961264
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/clr-find-bundle
cp LICENSE %{buildroot}/usr/share/doc/clr-find-bundle/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/find-bundle.sh

%files license
%defattr(-,root,root,-)
/usr/share/doc/clr-find-bundle/LICENSE
